type ExtraPrompt = {
  id: string;
  category: 'interview' | 'debate' | 'story' | 'pitch' | 'daily';
  text: string;
  hints: string[];
};

export const EXTRA_PROMPTS: ExtraPrompt[] = [
  {
    id: 'int-11',
    category: 'interview',
    text: 'Tell me about a time you had to say no to a stakeholder.',
    hints: ['Name the request', 'Show the tradeoff', 'How you kept the relationship'],
  },
  {
    id: 'int-12',
    category: 'interview',
    text: 'What do you do when you are bored at work?',
    hints: ['Be honest, not cute', 'Show self-direction', 'One example'],
  },
  {
    id: 'int-13',
    category: 'interview',
    text: 'Walk me through a decision you made with incomplete information.',
    hints: ['What you knew', 'What you guessed', 'What you’d do again'],
  },
  {
    id: 'int-14',
    category: 'interview',
    text: 'Describe a time you mentored someone who was struggling.',
    hints: ['Their stuck point', 'What you actually did', 'The result for them'],
  },
  {
    id: 'int-15',
    category: 'interview',
    text: 'Why this company — not a generic “I love the mission”?',
    hints: ['One specific thing they do', 'Why it fits you', 'What you’d add'],
  },
  {
    id: 'int-16',
    category: 'interview',
    text: 'Tell me about the last time you were wrong in public.',
    hints: ['Own it fast', 'What you corrected', 'No self-flagellation'],
  },
  {
    id: 'int-17',
    category: 'interview',
    text: 'How do you prioritize when everything is “urgent”?',
    hints: ['Your rule of thumb', 'One messy week', 'Who you told'],
  },
  {
    id: 'int-18',
    category: 'interview',
    text: 'What is something you are worse at than people assume?',
    hints: ['Name it cleanly', 'How you compensate', 'Keep dignity'],
  },
  {
    id: 'int-19',
    category: 'interview',
    text: 'Give me your 60-second career story — skip the resume list.',
    hints: ['One turning point', 'The thread', 'Why you’re here now'],
  },
  {
    id: 'int-20',
    category: 'interview',
    text: 'Tell me about a time you simplified something that was overcomplicated.',
    hints: ['The mess', 'The cut', 'Who it helped'],
  },
  {
    id: 'int-21',
    category: 'interview',
    text: 'How do you want to be managed?',
    hints: ['Be specific', 'One example of it working', 'One thing you don’t need'],
  },
  {
    id: 'int-22',
    category: 'interview',
    text: 'Describe a conflict you still think about.',
    hints: ['Stay fair', 'What you learned late', 'Close without bitterness'],
  },
  {
    id: 'deb-9',
    category: 'debate',
    text: 'Should unpaid internships be illegal?',
    hints: ['Who gets hurt', 'The best counter', 'A rule you’d write'],
  },
  {
    id: 'deb-10',
    category: 'debate',
    text: 'Is “hustle culture” mostly useful or mostly harmful?',
    hints: ['Define it', 'One real person', 'A nuanced close'],
  },
  {
    id: 'deb-11',
    category: 'debate',
    text: 'Should voting be mandatory?',
    hints: ['Pick a side in sentence one', 'Address apathy', 'Practical, not utopian'],
  },
  {
    id: 'deb-12',
    category: 'debate',
    text: 'Are group projects a good way to learn, or a tax on the competent?',
    hints: ['Your experience', 'When they work', 'A better design'],
  },
  {
    id: 'deb-13',
    category: 'debate',
    text: 'Should companies ban Slack after hours?',
    hints: ['The cost of always-on', 'The startup objection', 'A policy'],
  },
  {
    id: 'deb-14',
    category: 'debate',
    text: 'Is a personal brand a career skill or a trap?',
    hints: ['Who it helps', 'Who it hollows out', 'Your stance'],
  },
  {
    id: 'deb-15',
    category: 'debate',
    text: 'Should tips be replaced by living wages in restaurants?',
    hints: ['Workers first', 'Customer behavior', 'One concrete proposal'],
  },
  {
    id: 'deb-16',
    category: 'debate',
    text: 'Is college worth it if you already know what you want to build?',
    hints: ['Signal vs skill', 'An exception', 'Land the close'],
  },
  {
    id: 'sto-9',
    category: 'story',
    text: 'Tell the story of the first time you felt like an adult.',
    hints: ['A small scene', 'What changed', 'No speechifying'],
  },
  {
    id: 'sto-10',
    category: 'story',
    text: 'Recount a time you got lost — literally or otherwise.',
    hints: ['The moment of panic', 'What you did', 'The aftertaste'],
  },
  {
    id: 'sto-11',
    category: 'story',
    text: 'Tell a story about a teacher, coach, or boss who saw you before you did.',
    hints: ['What they said', 'Why it stung or stuck', 'What you did with it'],
  },
  {
    id: 'sto-12',
    category: 'story',
    text: 'Describe a night you should have gone home earlier.',
    hints: ['Sensory detail', 'The turn', 'What you still replay'],
  },
  {
    id: 'sto-13',
    category: 'story',
    text: 'Tell the story of a gift that meant more than it should have.',
    hints: ['The object', 'The person', 'Why it still lives with you'],
  },
  {
    id: 'sto-14',
    category: 'story',
    text: 'Share a moment you were underestimated — and what you did next.',
    hints: ['Don’t gloat', 'The quiet proof', 'End on the shift'],
  },
  {
    id: 'sto-15',
    category: 'story',
    text: 'Tell a two-minute story that starts with a sound.',
    hints: ['Open on the sound', 'Stay in scene', 'Close on meaning, not moral'],
  },
  {
    id: 'sto-16',
    category: 'story',
    text: 'Recount the last time you changed your mind about a person.',
    hints: ['First impression', 'The crack', 'Who they are now to you'],
  },
  {
    id: 'pit-9',
    category: 'pitch',
    text: 'Pitch a better way to run 1:1 meetings.',
    hints: ['The pain today', 'Your format', 'The ask: try it next week'],
  },
  {
    id: 'pit-10',
    category: 'pitch',
    text: 'Convince a friend to take a 10-day social media break with you.',
    hints: ['Start with their objection', 'Make it social', 'Low bar to start'],
  },
  {
    id: 'pit-11',
    category: 'pitch',
    text: 'Pitch yourself for a role you are not fully qualified for — honestly.',
    hints: ['The gap', 'The transfer', 'Why the bet is smart'],
  },
  {
    id: 'pit-12',
    category: 'pitch',
    text: 'Sell me on a neighborhood, city, or country as if I might move.',
    hints: ['Who it’s for', 'One vivid Tuesday', 'The catch'],
  },
  {
    id: 'pit-13',
    category: 'pitch',
    text: 'Pitch a tiny product that solves a frustration you had this week.',
    hints: ['The itch', 'The aha', 'Who pays'],
  },
  {
    id: 'pit-14',
    category: 'pitch',
    text: 'You have 45 seconds: get a busy person to mentor you.',
    hints: ['Why them', 'Why now', 'A tiny first ask'],
  },
  {
    id: 'pit-15',
    category: 'pitch',
    text: 'Pitch a family tradition you’d like to start.',
    hints: ['The feeling it creates', 'How small it is', 'Who has to buy in'],
  },
  {
    id: 'pit-16',
    category: 'pitch',
    text: 'Convince me to read a poem, not a business book, this month.',
    hints: ['Unexpected benefit', 'One line you’d quote', 'The ask'],
  },
  {
    id: 'day-13',
    category: 'daily',
    text: 'What are you over-explaining these days — and what would shorter sound like?',
    hints: ['Name the topic', 'Say the short version', 'Why you pad'],
  },
  {
    id: 'day-14',
    category: 'daily',
    text: 'Talk about a habit you dropped and whether you miss it.',
    hints: ['The habit', 'Why it ended', 'The honest residue'],
  },
  {
    id: 'day-15',
    category: 'daily',
    text: 'If your attention had a leak, where is it going?',
    hints: ['Be specific', 'The cost', 'One plug you’d try'],
  },
  {
    id: 'day-16',
    category: 'daily',
    text: 'Describe a conversation you keep postponing.',
    hints: ['Who', 'The sentence you’re avoiding', 'What starting looks like'],
  },
  {
    id: 'day-17',
    category: 'daily',
    text: 'What did you do today that nobody will notice — and why keep doing it?',
    hints: ['The small act', 'Who it serves', 'Keep it unheroic'],
  },
  {
    id: 'day-18',
    category: 'daily',
    text: 'Give a tour of a room you know well, as if I were closing my eyes.',
    hints: ['Three objects', 'One sound', 'How you feel in it'],
  },
  {
    id: 'day-19',
    category: 'daily',
    text: 'What would you teach a 16-year-old about money in two minutes?',
    hints: ['One rule', 'One mistake', 'No TED cadence'],
  },
  {
    id: 'day-20',
    category: 'daily',
    text: 'Talk about a time you were kind when it was inconvenient.',
    hints: ['The inconvenience', 'What you did', 'Don’t saint yourself'],
  },
  {
    id: 'day-21',
    category: 'daily',
    text: 'What’s a hill you used to die on that you quietly left?',
    hints: ['The old hill', 'What moved', 'What you believe now'],
  },
  {
    id: 'day-22',
    category: 'daily',
    text: 'Narrate your commute or your walk to the kitchen like a short documentary.',
    hints: ['Stay concrete', 'One human', 'End on a cut, not a lesson'],
  },
  {
    id: 'day-23',
    category: 'daily',
    text: 'If you could unsend one message from this year, which — and what would you send instead?',
    hints: ['The original', 'The better line', 'What you learned about tone'],
  },
  {
    id: 'day-24',
    category: 'daily',
    text: 'Explain a family rule you grew up with, then keep it or break it.',
    hints: ['The rule', 'What it protected', 'Your verdict'],
  },
  {
    id: 'int-23',
    category: 'interview',
    text: 'Tell me about a time you shipped something ugly on purpose.',
    hints: ['The constraint', 'The cut', 'What you protected'],
  },
  {
    id: 'int-24',
    category: 'interview',
    text: 'How do you recover after a meeting where you froze?',
    hints: ['The freeze', 'The repair', 'The prevention'],
  },
  {
    id: 'deb-17',
    category: 'debate',
    text: 'Should homework be abolished in high school?',
    hints: ['Equity', 'Practice vs busywork', 'A replacement'],
  },
  {
    id: 'deb-18',
    category: 'debate',
    text: 'Is it okay to ghost a recruiter?',
    hints: ['Power dynamics', 'Courtesy', 'Your rule'],
  },
  {
    id: 'sto-17',
    category: 'story',
    text: 'Tell a story that takes place entirely in a car.',
    hints: ['Who’s driving', 'The silence', 'The line that lands'],
  },
  {
    id: 'sto-18',
    category: 'story',
    text: 'Recount a time you waited for news.',
    hints: ['The waiting room', 'The body', 'The answer'],
  },
  {
    id: 'pit-17',
    category: 'pitch',
    text: 'Pitch a 20-minute weekly speaking club to skeptical coworkers.',
    hints: ['The meeting tax', 'The 2-minute bar', 'First session design'],
  },
  {
    id: 'pit-18',
    category: 'pitch',
    text: 'Convince someone to take the stairs with you for a month.',
    hints: ['Their objection', 'Make it easy', 'A visible payoff'],
  },
  {
    id: 'day-25',
    category: 'daily',
    text: 'What are you rehearsing in your head that you should just say?',
    hints: ['The line', 'The fear', 'Say a draft out loud now'],
  },
  {
    id: 'day-26',
    category: 'daily',
    text: 'Describe your taste — in music, food, or design — without using “I like.”',
    hints: ['Show, don’t list', 'One contrast', 'One scene'],
  },
  {
    id: 'day-27',
    category: 'daily',
    text: 'Talk for 90 seconds about a tool you use every day as if it were a character.',
    hints: ['Personality', 'How it fails you', 'Why you stay'],
  },
  {
    id: 'day-28',
    category: 'daily',
    text: 'What would a generous reading of your worst habit sound like?',
    hints: ['Name the habit', 'The need under it', 'A kinder next step'],
  },
  {
    id: 'int-25',
    category: 'interview',
    text: 'Why should we not hire you?',
    hints: ['A real gap', 'How you work around it', 'No fake humility'],
  },
  {
    id: 'deb-19',
    category: 'debate',
    text: 'Should offices exist in 2030?',
    hints: ['Timeframe', 'What offices are for', 'A conditional claim'],
  },
  {
    id: 'sto-19',
    category: 'story',
    text: 'Tell the story of a haircut, a scar, or a piece of clothing.',
    hints: ['The object', 'The before', 'The after'],
  },
  {
    id: 'pit-19',
    category: 'pitch',
    text: 'Pitch a better first date than dinner and drinks.',
    hints: ['The usual failure', 'Your format', 'Why it reveals more'],
  },
  {
    id: 'day-29',
    category: 'daily',
    text: 'If this week were graded, what would the teacher write in the comments?',
    hints: ['The grade', 'One strength', 'One note to improve'],
  },
  {
    id: 'day-30',
    category: 'daily',
    text: 'Speak a toast for someone who is not in the room.',
    hints: ['Name them', 'One scene', 'One wish', 'Stop'],
  },
  {
    id: 'int-26',
    category: 'interview',
    text: 'Walk me through a two-minute version of your career — turning points only, no resume recitation.',
    hints: ['One origin', 'One fork in the road', 'Why you’re here now'],
  },
  {
    id: 'int-27',
    category: 'interview',
    text: 'Tell me about a time you had to earn trust from people who didn’t want to give it.',
    hints: ['Why they resisted', 'What you actually did', 'When it shifted'],
  },
  {
    id: 'int-28',
    category: 'interview',
    text: 'Describe a messy project you still finished. Two minutes. Own the mess.',
    hints: ['The slip', 'Your call', 'What shipped'],
  },
  {
    id: 'int-29',
    category: 'interview',
    text: 'What do you want to be known for at work in two years — and what are you doing this month toward it?',
    hints: ['Name the reputation', 'One current habit', 'One gap'],
  },
  {
    id: 'deb-20',
    category: 'debate',
    text: 'Should we work in public more — sharing drafts, numbers, unfinished thinking? Argue for two minutes.',
    hints: ['Pick a side', 'One risk', 'One payoff', 'A rule you’d actually follow'],
  },
  {
    id: 'deb-21',
    category: 'debate',
    text: 'Is “busy” a compliment or a warning? Take a side and defend it for two minutes.',
    hints: ['Define busy', 'Who it serves', 'A better status signal'],
  },
  {
    id: 'deb-22',
    category: 'debate',
    text: 'Should companies ban meetings before 10am? Yes or no, then live with the consequences.',
    hints: ['Who wins', 'Who loses', 'A practical policy'],
  },
  {
    id: 'deb-23',
    category: 'debate',
    text: 'Advice is overrated. Most people need examples, not tips. Agree or disagree for two minutes.',
    hints: ['Your claim in sentence one', 'One story', 'The exception'],
  },
  {
    id: 'sto-20',
    category: 'story',
    text: 'Tell a two-minute story about the first time you felt like an adult — and whether it stuck.',
    hints: ['The moment', 'What you expected', 'What actually changed'],
  },
  {
    id: 'sto-21',
    category: 'story',
    text: 'Recount two minutes of a night that went off-script.',
    hints: ['The plan', 'The turn', 'How you left'],
  },
  {
    id: 'sto-22',
    category: 'story',
    text: 'Tell the story of a teacher, coach, or boss who changed your standards.',
    hints: ['One scene with them', 'The standard', 'Where it shows up now'],
  },
  {
    id: 'sto-23',
    category: 'story',
    text: 'Describe a place you keep going back to. Two minutes. Make me see it.',
    hints: ['Arrival', 'One sensory detail', 'Why it still works'],
  },
  {
    id: 'pit-20',
    category: 'pitch',
    text: 'Pitch a two-minute version of a product that already exists — as if it didn’t. Sell the problem first.',
    hints: ['Who hurts', 'The current hack', 'Your fix', 'The ask'],
  },
  {
    id: 'pit-21',
    category: 'pitch',
    text: 'You have two minutes: convince a friend to take a two-week break from their phone after 9pm.',
    hints: ['Their objection first', 'Make the first night tiny', 'What they get back'],
  },
  {
    id: 'pit-22',
    category: 'pitch',
    text: 'Pitch yourself for a role you are almost, but not quite, qualified for.',
    hints: ['The gap, honestly', 'The transferable proof', 'Why now'],
  },
  {
    id: 'day-31',
    category: 'daily',
    text: 'Talk for two minutes about a decision you are postponing — as if you had to choose tonight.',
    hints: ['The options', 'What you’re afraid of', 'A first move'],
  },
  {
    id: 'day-32',
    category: 'daily',
    text: 'Explain your last week to someone who cares, without using “busy” or “fine.” Two minutes.',
    hints: ['One high', 'One friction', 'What you want next week to hold'],
  },
  {
    id: 'day-33',
    category: 'daily',
    text: 'Teach a beginner how you actually start hard work. Two minutes. Skip the motivational poster.',
    hints: ['The first five minutes', 'What you ignore', 'How you know you’ve started'],
  },
  {
    id: 'day-34',
    category: 'daily',
    text: 'If a documentary crew followed you tomorrow, what would they misunderstand? Two minutes.',
    hints: ['The surface', 'What’s actually going on', 'One scene they’d miss'],
  },
  {
    id: 'day-35',
    category: 'daily',
    text: 'Talk for two minutes about money without bragging or apologizing.',
    hints: ['A rule you use', 'A mistake', 'What you’d tell a friend'],
  },
];
